import Header from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

const inter = Roboto({weight:"500" , subsets: ['vietnamese'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" id="tema" className='dark scroll-smooth'>
      <body className={`${inter.className} bg-gray-100 text-gray-700 dark:bg-sky-950 dark:text-gray-200`}>
        {children}
      </body>
    </html>
  )
}
